package main

import (
	"bufio"
	"fmt"
	"math/rand"
	"os"
	"strconv"
	"strings"
	"time"
)

var version = "0.0.2"

var ticketWfpCost = int64(500)
var prizes = []int{3000, 1000, 1000}

type Player struct {
	Name string
	Wfp  int64
}

func main() {
	rand.Seed(time.Now().UnixNano())

	file := openFile()
	defer file.Close()

	scanner := bufio.NewScanner(file)

	players := processFile(scanner)

	if err := scanner.Err(); err != nil {
		fatalError(err)
	}

	tickets := []*Player{}

	for _, player := range players {
		numberOfTickets := player.Wfp / ticketWfpCost

		fmt.Printf(playerUrl(player.Name)+" %v\n", numberOfTickets)
		for i := int64(0); i < numberOfTickets; i++ {
			tickets = append(tickets, player)
		}
	}

	rand.Shuffle(len(tickets), func(i, j int) { tickets[i], tickets[j] = tickets[j], tickets[i] })

	fmt.Println("\nResults\n")

	previousWinners := []int{}

	for i := 0; i < len(prizes); i++ {
		for len(previousWinners) <= i {
			winner := random(0, len(tickets))
			if !stringInSlice(winner, previousWinners) {
				previousWinners = append(previousWinners, winner)
				fmt.Println(fmt.Sprintf("%v", prizes[i]) + "c " + playerUrl(tickets[winner].Name))
				continue
			}
		}
	}

	fmt.Println("\nGenerated by [url]https://github.com/benjih/weekly-wfp-calculator[/url] " + version)

	waitForClose()
}

func openFile() *os.File {
	file, err := os.Open("wfp.txt")
	if err != nil {
		fatalError(err)
	}
	return file
}

func random(min, max int) int {
	return rand.Intn(max-min) + min
}

func stringInSlice(a int, list []int) bool {
	for _, b := range list {
		if b == a {
			return true
		}
	}
	return false
}

func playerUrl(name string) string {
	return fmt.Sprintf("[url=https://www.legacy-game.net/profile.php?p=%[1]s]%[1]s[/url]", name)
}

func waitForClose() {
	fmt.Print("\nPress any key to continue...")
	bufio.NewReader(os.Stdin).ReadBytes('\n')
}

func fatalError(err error) {
	fmt.Println(err.Error())
	waitForClose()
}

func processFile(scanner *bufio.Scanner) []*Player {
	players := []*Player{}
	for scanner.Scan() {
		text := scanner.Text()
		i := strings.Index(text, "[")
		for i != -1 {
			k := strings.Index(text, "]")

			text = text[:i] + text[k+1:]
			i = strings.Index(text, "[")
		}
		fields := strings.Fields(text)

		wfp, _ := strconv.ParseInt(strings.Replace(fields[3], ",", "", -1), 10, 64)
		player := &Player{Name: fields[1], Wfp: wfp}
		players = append(players, player)
	}

	return players
}
